import type { Metadata } from "next";
import { Anton, Inter } from 'next/font/google';

import "./globals.css";
import LenisProvider from "./providers/lenis.provider";

export const anton = Anton({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-anton',
});

const inter = Inter({
  subsets: ['latin'],
  display: 'swap', 
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "Ranjit Shrestha - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${anton.variable} ${anton.className} antialiased`}>
        <LenisProvider>
          {children}
        </LenisProvider>
      </body>
    </html>
  );
}